### ISSUE TITLE
Does not work with Docker

### ISSUE THREAD

**Issue by rogeralsing** [couchbase/go-couchbase#76] opened 2016-09-26 07:10 UTC
I'm running my Couchbase server in Docker with port mapping to my local machine for development.
This works fine for the .NET SDK, however, when using this Go SDK, the SDK tries to talk to the Docker IP.

```
2016/09/26 09:03:27 dial tcp 172.17.0.2:11210: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
exit status 1
```

The `172.17.0.2` is the internal IP for the container, and is not accessible from the outside.
Do note that this is not the IP I provided when trying to connect to the server:
I provided `http://localhost:8091`, 

Does this mean that we cannot use Couchbase hosted in Docker for development environments?

**Comment by tleyden** [comment] 2016-09-26 16:51
I've used [sync gateway](https://github.com/couchbase/sync_gateway) with docker fairly extensively with no observed issues, and sync gateway uses go-couchbase to connect to Couchbase Server.

Can you post some code samples of how you are initializing go-couchbase?  In particular which hostname are you passing it?

Also, do you have multiple containers or are you running go-couchbase on the same container as couchbase-server?

**Comment by rogeralsing** [comment] 2016-10-02 07:22
I'm running the Go application locally on my machine, trying to access couchbase inside a port mapped docker container.
That is, I'm communicating with Coucbase as if it was on localhost, while it is actually inside a container.

Doing so results in the error described above, the CB server seems to leak the internal container IP out to the client, which ofc cannot communicate from the host into the container directly.

I have switched to the GOCB lib instead for now, which do work fine with this set up.

**Comment by rogeralsing** [comment] 2016-10-02 07:25
Code example to replicate this, just using the one on the readme here

```go
c, err := couchbase.Connect("http://localhost:8091/")
if err != nil {
    log.Fatalf("Error connecting:  %v", err)
}

pool, err := c.GetPool("default")
if err != nil {
    log.Fatalf("Error getting pool:  %v", err)
}

bucket, err := pool.GetBucket("default")
if err != nil {
    log.Fatalf("Error getting bucket:  %v", err)
}
```

Running this on the host machine, while the CB server is inside a portmapped container will fail.

**Comment by brspurri** [comment] 2016-10-06 21:28
Seeing the same issue. +1

**Comment by tleyden** [comment] 2016-10-11 16:08
Where are you running the executable that calls go-couchbase?  Inside the container running Couchbase Server, on the host, or in another container that is running side by side with the Couchbase Server container?

**Comment by asaf** [comment] 2016-11-11 23:03
This is still not working.

When starting Couchbase via docker it adds one node which receives the IP address of the docker instance (172.17.0.2 by default)),

Since `couchbase.Connect("http://localhost:8091/")` connects to the pool, it receives the node IP address and timeouts since `172.17.0.2` is not accessible via the docker's host machine.

Is there a way to change the node's ip address being published or connect directly to a node instead of the pool?


Thanks

**Comment by tleyden** [comment] 2016-11-11 23:34
@asaf I need as much info as possible as to how you are trying to run this in order to help.  If I were to reproduce your problem from scratch, what would be the step by step?

It *sounds* like you are using a different form of networking than is expected by the code in this repo.  For example, if you are running this as a sidecar container on the same host, you'll need to run both the Couchbase container and the go-couchbase container with `--net=host` in order to facilitate localhost connections between the two containers.  (the reason it works is because both containers essentially gain direct access to the host's network interface rather than being relegated to a bridged subnet with their own ip addresses like `172.17.0.2`.

**Comment by tleyden** [comment] 2016-11-11 23:35
I'm closing this because I'm not seeing a clear-cut bug in the go-couchbase repo that is actionable.  Feel free to continue the discussion here though!

**Closed by tleyden** 2016-11-11 23:35 UTC

**Comment by asaf** [comment] 2016-11-13 21:41
@tleyden I think it was clear when I said "via the docker's host machine", not a side by side container. Anyway I solved this by providing another url for the host instead of localhost during the installation, this causes the first node to have a dns name instead of IP address.

**Comment by contacttapan** [comment] 2017-12-06 18:45
@asaf I am facing exactly the same issue, when u say provided another URL , where is your docker couchbase running. Is it running on local or its running remotely .And how did you provide host while installion , did you use --network(bridge) of docker.Please suggest.

**Comment by tleyden** [comment] 2017-12-08 18:45
@davefinlay -- is this related to the bootstrapping problem you mentioned?

@contacttapan would it be possible to run go-couchbase in another container in the same docker network as the couchbase server cluster?  That should fix any routing issues you are running into.

**Comment by contacttapan** [comment] 2017-12-09 06:19
I am running on my mac , and couch is running in separate docker.
Finally able to solve it by running loopback ip to localhost 
ifconfig lo0 alias 172.17.0.2
